version: "2"
services:
    web:
        build: docker/web
        links:
            - db
            - mail
        volumes:
            - ./:/app
        ports:
            - "8080:8080"
            - "8081:8081"
    db:
        image: "mysql:5.6"
        environment:
            MYSQL_ROOT_PASSWORD: sample
            MYSQL_DATABASE: sample
            MYSQL_USER: sample
            MYSQL_PASSWORD: sample
        ports:
            - "3306:3306"

    nodejs:
        build: ./docker/nodejs
        volumes:
            - ./:/app
