version: "2"
services:
    web:
        build: docker/web
        links:
            - db
        volumes:
            - ./:/app
        ports:
            - "8080:8080"
    db:
        image: "mysql:5.7"
        environment:
            MYSQL_ROOT_PASSWORD: homestead
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"

    nodejs:
        build: ./docker/nodejs
        volumes:
            - ./:/app
